enableGlobalCache: true

# Prevent hoisting. All dependencies are installed in their respective
# workspace's node_modules folder.
nmHoistingLimits: workspaces

nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.2.0.cjs